version: '3'

services:
    database:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: codetube
            MYSQL_USER: dmitry
            MYSQL_PASSWORD: codetube
            MYSQL_DATABASE: codetube
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    python:
        build: python
        command: python3 manage.py runserver 0.0.0.0:8000
        #command: uwsgi --socket :8001 --module src.wsgi
        volumes:
            - .:/codetube
            - .aws:/root/.aws
        ports:
            - 8000:8000
            - 8001:8001
        depends_on:
            - database

    nginx:
        build: nginx
        links:
          - python
        ports:
            - 80:80
        volumes:
            - .:/codetube
        depends_on:
            - python


