version: '3'

services:
  database:
    image: mysql:latest
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  python:
    build: ./docker/python
    #command: python3 manage.py runserver 0.0.0.0:8000
    command: uwsgi --ini uwsgi.ini
    volumes:
      - .:/codetube
      - ./aws/:/root/.aws
    environment:
      NAME: ${MYSQL_DATABASE}
      USER: ${MYSQL_USER}
      PASSWORD: ${MYSQL_PASSWORD}
      HOST: database
    ports:
      - 8000:8000
      - 8001:8001
    depends_on:
      - database

  nginx:
    build: ./docker/nginx
    links:
      - python
    ports:
      - 80:80
    volumes:
      - .:/codetube
      - ./docker/nginx/log:/var/log/nginx
    depends_on:
      - python

  node:
    build: ./docker/node
    volumes:
      - .:/codetube
    ports:
      - 8080:8080
    command: bash -c "if [ ! -d "app"  ]; then vue create app -d && cd app && yarn serve; else cd app && yarn serve; fi"




