version: '3'

services:
    database:
        image: mysql:latest
        ports:
            - 3306:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
        environment:
            MYSQL_ROOT_PASSWORD: codetube
            MYSQL_USER: dmitry
            MYSQL_PASSWORD: codetube
            MYSQL_DATABASE: codetube
    python:
        build: python
        #command: python3 manage.py runserver 0.0.0.0:8000
        command: uwsgi --ini uwsgi.ini
        volumes:
            - .:/codetube
            - ./aws/:/root/.aws
        ports:
            - 8000:8000
            - 8001:8001
        depends_on:
            - database

    nginx:
        build: nginx
        links:
          - python
        ports:
          - 80:80
        volumes:
           - .:/codetube
           - ./data/nginx/log:/var/log/nginx
        depends_on:
            - python


