version: '3'

services:
    database:
        image: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: codetube
            MYSQL_DATABASE: codetube
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        #restart: always
        volumes:
            - .:/codetube
        ports:
            - 8000:8000
            #- 80:80
        depends_on:
            - database

