# Generated by Django 2.0.1 on 2018-03-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='visibility',
            field=models.CharField(choices=[('p', 'Public'), ('u', 'Unlisted'), ('pr', 'Private')], max_length=255),
        ),
    ]
