# Generated by Django 2.0.1 on 2018-03-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180318_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='visibility',
            field=models.CharField(choices=[('1', 'Public'), ('2', 'Unlisted'), ('3', 'Private')], default=1, max_length=255),
        ),
    ]
